### ISSUE TITLE
EXTENDED_LINKED_SHUTTER implementation details missing?

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#258]
Hi,
i've searched for a definition of an `EXTENDED_LINKED_SHUTTER` (`ExtendedLinkedShutterGroup`) and found it in #198.
It looks like `shutterLevel` is not used. (??)
Instead it looks like `topShutterLevel` and `topSlatsLevel` are the one to be used.
Could you please check if there are also service calls to control the `slatsLevel`?
Like `device/control/setSlatsLevel?` 

BR
Markus

**Comment by coreGreenberet** [comment]
top/bottom shutter/slats level are configured/calibrated.
slats/shutterLevel should be the current one. To be honest I don't know why it was null here

there are /group/switching/setGroupShutterLevel and /group/switching/setGroupSlatsLevel

both require a groupId & shutterLevel
setGroupSlatslevel requires an additional slatsLevel parameter (similiar to /device/control/setSlatsLevel)

I can implement both of them, but I can't test them out, because I don't own the required actors

**Comment by SukramJ** [comment]
I don't own it too, so i rely on your work. 
Do you know someone how could test it?

**Comment by coreGreenberet** [comment]
I've implemented the slats level request in PR #259 
Maybe I can find someone to test it, before I merge it

**Comment by SukramJ** [comment]
Thanks.
