### ISSUE TITLE
Wall-mount Remote Control for brand switches (HmIP-BRC-2)

### ISSUE THREAD

**Issue by bonsaijogi** [coreGreenberet/homematicip-rest-api#292]
Today I noticed that the HmIP-BRC-2 is not integrated in Home Assistant. It is listed together with the WRC-2, but does not appear in HA.

It would be nice if the HmIP-BRC-2 wall switch could also be integrated.

Thank you very much

[hmip_config.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/4112461/hmip_config.txt)

**Comment by SukramJ** [comment]
HmIP-BRC2 is already added to this lib, but there is nothing to be added to HA. 
WRC2 is only visible by its battery binary_sensor.

The Pushbutton functionality cannot be used by HA, because the eQ-3-API does nor deliver any useful information like which button has  been pressed or how (short/long).
As long as eQ-3 does not update their API there is nothing to be done here or HA.
BR

**Comment by bonsaijogi** [comment]
ah, OK, i understand, thanks anyway
