### ISSUE TITLE
Offtopic: Reverse Engeneering

### ISSUE THREAD

**Issue by Phreak87** [coreGreenberet/homematicip-rest-api#317]
Great work! 

can you please tell something about how you got the implementation details from
the cloud connection? havo you soldered out some ic`s or just by listening to the
communincation from a mobile phone? which tools you have used for this?
i like to go deeper into this device - and maybe i find something to raise the Alarm.

thank you so much for this great library!

**Comment by coreGreenberet** [comment]
I've started with Charles/Fiddler (HTTPS Proxy) and listened to the communication between my phone and the cloud.
However sooner or later I had to decompile the apk and I had to implement the needed methods from the decompiled java source basically because of 3 reasons
1) EQ3 had started to use certificate pinning, so my root ca from fiddler/charles wasn't working anymore
2) EQ3 has changed the hash algorith for the tokens. They've added a salt in the code. Without looking at the code it would have been impossible to authenticate again.
3) ENUMS!! You can't know every possible value from the device states just by looking at the communication/current state of the values. The enums are in the java source files, so I'm able to easily convert them to python enums =)

**Comment by Phreak87** [comment]
Great! 

thank you for the information. I try to port your Project to C# for integrations
to other Home-Automatism Software. EQ3 makes also a very good job and make
the system very secure. Have you ever tried to modify the Firmware of the AP? 
That would be great if this would work. because i hate all the insecure
cloud-based hardware.

**Comment by coreGreenberet** [comment]
Nope, my intention wither api was never to modify the firmware or to replace the cloud.
I've started with it, because I had a water well for the cats and it was too loud in the night. So i shut it down via a cronjob at midnight 😂

**Comment by steckenpferd** [comment]
@Phreak87 there is already a gihub page for the HmIP Cloud C# porting exisitng
https://github.com/larsbeck/HomematicIp
